# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKcKk8AcsPJdndI0bNIFOr7J6M8j14Ws
"""

import pandas as pd
import numpy as np

from project_paths import BERT_LOGS_DIR, BERT_RESULTS_DIR, PROJECT_ROOT, RAW_DATA_DIR, first_existing_path

book_path = first_existing_path(RAW_DATA_DIR / "Book1.xlsx", PROJECT_ROOT / "Book1.xlsx")
df = pd.read_excel(book_path)

from sklearn.model_selection import train_test_split

# X = features, y = target
X = df.drop(columns=['severity'])
y = df['severity']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,      # 20% test
    random_state=42,    # reproducibility
    stratify=y          # use this if classification
)

print(X_train.shape, X_test.shape)

df.head(5)

# Commented out IPython magic to ensure Python compatibility.
# %pip install transformers datasets torch scikit-learn

import pandas as pd

# Define label mappings
unique_labels = sorted(y_train.unique().tolist())
label2id = {label: i for i, label in enumerate(unique_labels)}
id2label = {i: label for i, label in enumerate(unique_labels)}

# Convert y_train to numerical labels
y_train_encoded = y_train.map(label2id)

train_df = pd.DataFrame({
    "text": X_train['grievance_text'],
    "label": y_train_encoded # Use encoded labels
})

from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

def tokenize(example):
    return tokenizer(
        example['text'],
        padding='max_length',
        truncation=True,
        max_length=128
    )

from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
train_dataset = train_dataset.map(tokenize, batched=True)

train_dataset = train_dataset.rename_column("label", "labels")
train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

from transformers import BertForSequenceClassification

model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=len(unique_labels), # Use len(unique_labels) from earlier
    id2label=id2label,
    label2id=label2id
)

import torch
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir=str(BERT_RESULTS_DIR),
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir=str(BERT_LOGS_DIR),
    logging_steps=10,
    use_cpu=not torch.cuda.is_available()
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset
)

trainer.train()

# Encode y_test with numerical labels
y_test_encoded = y_test.map(label2id)

# Create a DataFrame for the test set
test_df = pd.DataFrame({
    "text": X_test['grievance_text'],
    "label": y_test_encoded
})

# Convert to Hugging Face Dataset
test_dataset = Dataset.from_pandas(test_df)

# Tokenize the test dataset
test_dataset = test_dataset.map(tokenize, batched=True)

# Rename the label column and set the format
test_dataset = test_dataset.rename_column("label", "labels")
test_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

# Evaluate the model
results = trainer.evaluate(test_dataset)
print(results)

# Make predictions on the test dataset
predictions_output = trainer.predict(test_dataset)
predicted_labels = np.argmax(predictions_output.predictions, axis=1)
true_labels = predictions_output.label_ids

from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, precision_score, roc_auc_score
from scipy.special import softmax
import matplotlib.pyplot as plt
import seaborn as sns

# Generate the confusion matrix
cm = confusion_matrix(true_labels, predicted_labels)

# Plot the confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=unique_labels, yticklabels=unique_labels)
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Calculate Precision (weighted)
# Set zero_division=0 to explicitly handle cases where no samples are predicted for a label,
# setting their precision to 0, which also suppresses the UndefinedMetricWarning.
precision = precision_score(true_labels, predicted_labels, average='weighted', zero_division=0)
print(f"Model Precision (weighted): {precision}")

# Calculate AUC
# Get raw logits from predictions_output
logits = predictions_output.predictions

# Apply softmax to get probabilities for each class
probabilities = softmax(logits, axis=1)

# Calculate AUC using 'ovr' (one-vs-rest) strategy for multi-class classification
# Ensure labels are one-hot encoded for roc_auc_score if not already.
# Since we have integer labels, roc_auc_score can handle it directly with multi_class='ovr'
auc = roc_auc_score(true_labels, probabilities, multi_class='ovr', average='weighted')
print(f"Model AUC (weighted, ovr): {auc}")

# Calculate accuracy
accuracy = accuracy_score(true_labels, predicted_labels)
print(f"Model Accuracy: {accuracy}")

# Calculate F1-score
f1 = f1_score(true_labels, predicted_labels, average='weighted')
print(f"Model F1-score (weighted): {f1}")
